### Get article by id
GET http://localhost:3000/api/articles/-H91UO1mzYQSeSGK2rxWC

### Create new article
POST http://localhost:3000/api/articles/
Content-Type: application/json

{
  "announce": "Игры и программирование разные вещи. Не стоит идти в программисты, если вам нравится только игры.  1938 году.",
  "category": [
    "Железо",
    "За жизнь"
  ],
  "createdDate": "2020-03-27T07:48:50.808Z",
  "fullText": "Освоить вёрстку несложно.",
  "title": "Как собрать камни бесконечности"
}

### Update Article
PUT http://localhost:3000/api/articles/-H91UO1mzYQSeSGK2rxWC
Content-Type: application/json

{
  "announce": "Игры и программирование разные вещи. Не стоит идти в программисты, если вам нравится только игры.  1938 году.",
  "category": [
    "Железо",
    "За жизнь"
  ],
  "createdDate": "2020-03-27T07:48:50.808Z",
  "fullText": "Освоить вёрстку несложно.",
  "title": "Как собрать камни бесконечности"
}
