export {adminPublicationsRouter} from "./admin-publications.router";
export {articlesRouter} from "./articles.router";
export {categoriesRouter} from "./categories.router";
export {mainPageRouter} from "./main-page.router";
export {registrationRouter} from "./registration.router";
export {searchRouter} from "./search.router";
export {signInRouter} from "./sign-in.router";
export {commentsRouter} from "./comments.router";
export {signOutRouter} from "./sign-out.router";
