### Get user by id
GET http://localhost:3000/api/users/2


### Create new user
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "email": "zaberkird1er81@usgs.gov",
  "firstName": "Lowe",
  "lastName": "Tennant",
  "avatar": "",
  "roleId": 2,
  "password": "123456",
  "passwordRepeated": "123456"
}
