const MS_IN_DAY = 86400000;
const MS_IN_HOUR = 3600000;
const MS_IN_MINUTE = 60000;
const MINUTES_IN_HOUR = 60;
const DAYS_IN_WEEK = 7;
const DAYS_IN_MONTH = 30;

export = {
  MS_IN_DAY,
  MS_IN_HOUR,
  MS_IN_MINUTE,
  MINUTES_IN_HOUR,
  DAYS_IN_WEEK,
  DAYS_IN_MONTH,
};
